POST http://localhost:8080/signup

{
    "email": "555",
    "password": "321"
}
####
POST http://localhost:8080/login

{
    "email": "555",
    "password": "321"
}

#### protected
GET http://localhost:8080/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjU1NSIsImlzcyI6ImNvdXJzZSJ9.-RRHtPussaQrpRtQOgZIwTQ31u-5-Bq-eV866U4L3AU
